language: python
python:
  - "3.6"
before_install:
- pip install poetry
script: poetry run pytest --flake8 --cov=dfa --cov-report=html -n2
cache:
  directories:
    - ${HOME}/.cache/pip
after_success:
  - codecov
